# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BuddyBuild_iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Fabric'
  # Pods for BuddyBuild_iOS

  target 'BuddyBuild_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuddyBuild_iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
